version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: JbjFOlrv
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    volumes:
      - ./images:/app/imagenes

  adminer:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 80:8080


volumes:
  postgres_data:
